### ISSUE TITLE
lofar-beam doesn't have stationresponse

### ISSUE THREAD

**Issue by bennahugo** [kernsuite/packaging#197] opened 2019-04-03 10:07 UTC
Trying to port DDF to KERN5, but running into a beams issue:
```
  File "/usr/local/bin/DDF.py", line 367, in <module>
    main(OP, messages)
  File "/usr/local/bin/DDF.py", line 209, in main
    Imager.Init()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 268, in Init
    AverageBeamMachine=ClassBeamMean.ClassBeamMean(self.VS)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Data/ClassBeamMean.py", line 70, in __init__
    JonesMachine.InitBeamMachine()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Data/ClassJones.py", line 629, in InitBeamMachine
    self.BeamMachine = ClassLOFARBeam.ClassLOFARBeam(self.MS, self.GD)
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Data/ClassLOFARBeam.py", line 33, in __init__
    self.InitLOFARBeam()
  File "/usr/local/lib/python2.7/dist-packages/DDFacet/Data/ClassLOFARBeam.py", line 44, in InitLOFARBeam
    import lofar.stationresponse as lsr
ImportError: No module named lofar.stationresponse
```

Lofarbeams are installed:
```
....
Setting up python-secretstorage (2.3.1-2) ...
Setting up lofarbeam-dev (4.0-1kern2) ...
Setting up python-keyring (10.6.0-1) ...
....
```

**Comment by gijzelaerr** [comment] 2019-04-03 10:53
The station response package doesn't contain the python module, this is still part of the old lofar suite. The lofar suite is not ported to casacore 3 yet, so we can't add it to kern-5. For now I recommend to use KERN-4 or wait till the lofar code has been ported.

I'm not sure what the current state of this is, but my astron contact person @tammojan is not available for now.

**Comment by bennahugo** [comment] 2019-04-03 10:57
Sure no problem. I will try building this specific module from source for now

**Comment by bennahugo** [comment] 2019-04-03 11:08
Ok no I can confirm the last release of the stationresponse is not compatible with the current casacore.

**Comment by bennahugo** [comment] 2019-04-03 11:30
Nor does it build successfully with KERN4

**Comment by gijzelaerr** [comment] 2019-04-03 11:32
i can't help you without an error message.

**Comment by gijzelaerr** [comment] 2019-04-26 12:29
duplicate of https://github.com/kernsuite/packaging/issues/181

**Closed as completed by gijzelaerr** 2019-04-26 12:29 UTC
Labels: bug
