### ISSUE TITLE
chgcentre Illegal instruction (core dumped) due wrong compilation.

### ISSUE THREAD

**Issue by Chanka2019** [kernsuite/packaging#216] opened 2020-03-03 11:07 UTC
Hello, 

I am trying to change the phase centre of the HERA measurement set using 'chgcentre tool', after running the command: chgcentre zen.2458115.31193_split.ms 03h30m53.1s -30d46m38.74s

I got a warning: chgcentre Illegal instruction (core dumped) due to wrong compilation

I had to get in touch with Andre Offringa, and below is his comment

This probably has to do with your setup, as your command works fine on my machine with your measurement set. If you compile chgcentre on one machine, and run it on another (which is the most common cause of an 'illegal instruction' error that you get), you have to pass "-DPORTABLE=True" to cmake during compilation.

**Comment by gijzelaerr** [comment] 2020-03-03 11:53
hi! Thanks for reporting this. But this is actually a duplicate of https://github.com/kernsuite/packaging/issues/195

We hope to solve this issue in a future KERN release at some point.

**Closed as completed by gijzelaerr** 2020-03-03 11:53 UTC
