### ISSUE TITLE
where has lofar gone?

### ISSUE THREAD

**Issue by bennahugo** [kernsuite/packaging#190] opened 2019-02-14 15:47 UTC
E: Package 'lofar' has no installation candidate on KERN 5

This package contains the various subpackages needed for imaging, including the beams.

**Comment by bennahugo** [comment] 2019-02-14 15:50
I see things are split out, but there is no metapackage anymore?

**Comment by gijzelaerr** [comment] 2019-02-18 07:21
KERN-5 is based on casacore 3 and nobody took the effort to port the LOFAR tree to this casacore yet.

closing this issue since it is a duplicate of https://github.com/kernsuite/packaging/issues/181

**Closed as completed by gijzelaerr** 2019-02-18 07:21 UTC
Labels: bug
