### ISSUE TITLE
wsclean/casacore deps clusterfuck

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#27] opened 2017-02-11 10:05 UTC
So I have a 16.04 system. Got this installed:
```
oms@ike:~/projects/IH-VLA/14A-012/MACSJ0416-S$ dpkg -la|grep casa
ii  casacore-data                        20160711-1kern1                          all          Casacore data files
ii  casarest                             1.4.1-1kern3                             amd64        standalone radio interferometric imager derived from CASA
ii  libcasa-casa2:amd64                  2.1.0-1kern2                             amd64        CASA core modules
ii  libcasa-coordinates2:amd64           2.1.0-1kern2                             amd64        CASA coordinates library
ii  libcasa-fits2:amd64                  2.1.0-1kern2                             amd64        CASA FITS library
ii  libcasa-images2:amd64                2.1.0-1kern2                             amd64        CASA image processing library
ii  libcasa-lattices2:amd64              2.1.0-1kern2                             amd64        CASA lattice library
ii  libcasa-measures2:amd64              2.1.0-1kern2                             amd64        CASA measures library
ii  libcasa-mirlib2:amd64                2.1.0-1kern2                             amd64        CASA mirlib library
ii  libcasa-ms2:amd64                    2.1.0-1kern2                             amd64        CASA MeasurementSet library
ii  libcasa-python2:amd64                2.1.0-1kern2                             amd64        CASA Python bindings
ii  libcasa-scimath-f2:amd64             2.1.0-1kern2                             amd64        CASA scimath F library
ii  libcasa-scimath2:amd64               2.1.0-1kern2                             amd64        CASA basic mathematical modules
ii  libcasa-tables2:amd64                2.1.0-1kern2                             amd64        CASA table system
ii  python-casacore                      2.1.2-1kern2                             amd64        python wrapper for casacore
$
```

Now I want to install wsclean:

```
$ sudo apt-get install wsclean
[sudo] password for oms: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-53 linux-headers-4.4.0-53-generic linux-headers-4.4.0-57 linux-headers-4.4.0-57-generic
  linux-image-4.4.0-53-generic linux-image-4.4.0-57-generic linux-image-extra-4.4.0-53-generic linux-image-extra-4.4.0-57-generic
  linux-signed-image-4.4.0-53-generic linux-signed-image-4.4.0-57-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libboost-date-time1.58.0 libcommon libelementresponse libgsl2 liblog4cplus-1.1-9 libstationresponse libwsclean0
Suggested packages:
...
```
Running wsclean gives an error (***NB: if you just run it without parameters it's ok, it prints the help text. It's actually getting it to open an MS that forces the error.***)
```
$ wsclean foo.ms
wsclean: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwsclean.so.0: undefined symbol: _ZN4casa7QuantumIdEC1Ev
```
Next, I install ``casacore-dev`` to make wsclean work:
```
$ sudo apt-get install casacore-dev
[sudo] password for oms: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-53 linux-headers-4.4.0-53-generic linux-headers-4.4.0-57 linux-headers-4.4.0-57-generic
  linux-image-4.4.0-53-generic linux-image-4.4.0-57-generic linux-image-extra-4.4.0-53-generic linux-image-extra-4.4.0-57-generic
  linux-signed-image-4.4.0-53-generic linux-signed-image-4.4.0-57-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libcasa-casa2 libcasa-coordinates2 libcasa-derivedmscal2 libcasa-fits2 libcasa-images2 libcasa-lattices2 libcasa-meas2
  libcasa-measures2 libcasa-mirlib2 libcasa-ms2 libcasa-msfits2 libcasa-python2 libcasa-scimath-f2 libcasa-scimath2 libcasa-tables2
The following NEW packages will be installed:
  casacore-dev libcasa-derivedmscal2 libcasa-meas2 libcasa-msfits2
The following packages will be upgraded:
  libcasa-casa2 libcasa-coordinates2 libcasa-fits2 libcasa-images2 libcasa-lattices2 libcasa-measures2 libcasa-mirlib2 libcasa-ms2
  libcasa-python2 libcasa-scimath-f2 libcasa-scimath2 libcasa-tables2
```
But now pyrap-measures is broken:
```
$ python -c "import pyrap.measures"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pyrap/measures.py", line 1, in <module>
    from casacore.measures import *
  File "/usr/lib/python2.7/dist-packages/casacore/measures/__init__.py", line 30, in <module>
    import casacore.quanta as dq
  File "/usr/lib/python2.7/dist-packages/casacore/quanta/__init__.py", line 1, in <module>
    from .quantity import quantity, is_quantity
  File "/usr/lib/python2.7/dist-packages/casacore/quanta/quantity.py", line 2, in <module>
    from ._quanta import Quantity
ImportError: /usr/lib/python2.7/dist-packages/casacore/quanta/_quanta.x86_64-linux-gnu.so: undefined symbol: _ZN4casa16throwArrayShapesEPKc
```
Upgrading python-casacore solves it:
```
oms@ike:~/projects/IH-VLA/14A-012$ sudo apt-get install python-casacore
Reading package lists... Done  dependencies not installed?
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-53 linux-headers-4.4.0-53-generic linux-headers-4.4.0-57 linux-headers-4.4.0-57-generic
  linux-image-4.4.0-53-generic linux-image-4.4.0-57-generic linux-image-extra-4.4.0-53-generic linux-image-extra-4.4.0-57-generic
  linux-signed-image-4.4.0-53-generic linux-signed-image-4.4.0-57-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  python-casacore
```
But now ``casacore-data`` is also required, but it hasn't been installed. Once I install that, I finally have a working system (I think....)

**Comment by o-smirnov** [comment] 2017-02-11 10:09
Nope, I now have a broken pyrap.measures:

``` File "/home/oms/projects/DDFacet/DDFacet/Data/ClassFITSBeam.py", line 164, in getBeamSampleTimes
    dm.posangle(self.field_centre,self.zenith).get_value("deg") for t0 in beam_times ]
  File "/usr/lib/python2.7/dist-packages/casacore/measures/__init__.py", line 933, in posangle
    return _measures.posangle(self, m0, m1)
RuntimeError: 2017-02-11 10:06:59       SEVERE  MeasTable::dUTC(Double) (file /build/casacore-M1hmay/casacore-2.2.0/measures/Measures/MeasTable.cc, line 4383)       Cannot read leap second table TAI_UTC
```

**Comment by o-smirnov** [comment] 2017-02-11 10:16
OK, old school now, adding this to my ``~/.casarc`` solves the measures problem. Looks like the default paths to the data tables are not compiled into casacore correctly.

```
measures.DE200.directory: /usr/share/casacore/data/ephemerides
measures.DE405.directory: /usr/share/casacore/data/ephemerides
measures.line.directory: /usr/share/casacore/data/ephemerides
measures.sources.directory: /usr/share/casacore/data/ephemerides
measures.comet.directory: /usr/share/casacore/data/ephemerides
measures.ierseop97.directory: /usr/share/casacore/data/geodetic
measures.ierspredict.directory: /usr/share/casacore/data/geodetic
measures.tai_utc.directory: /usr/share/casacore/data/geodetic
measures.igrf.directory: /usr/share/casacore/data/geodetic
measures.observatory.directory: /usr/share/casacore/data/geodetic
```

**Comment by gijzelaerr** [comment] 2017-02-13 07:37
so first of all, in case of these problems you need to make sure you have updated your packages. You were using a `wsclean` that was compiled against an older version of `casacore`. I'm not sure if I can force the binary dependency relationship but I prefer not to do that since that probably adds a lot of maintenance admin. Secondly `casacore` and `python-casacore` don't depend on `casacore-data` by design. lastly it looks like @olebole changed the default location of the casacore data for Debian and pushed those to the KERN. the KERN casacore-data packages are still installed in `/usr/share`. I'll update the default location, this means will have to remove the `.casarc` file again when you update. The casacore-data packages are updated once a week.

**Comment by gijzelaerr** [comment] 2017-02-13 08:00
here is the change:
https://github.com/kernsuite-debian/casacore/commit/7f645e7a691e08407f81a7286ad2edaf640c24b8#diff-d2b2229a977ef7e99780f2207c29b503L14
so for 2.2.0 packages (kern-dev) it is `/var/lib/` and for 2.1.0 packages (kern-1) it is `/usr/share/`. I don't understand why you need to set it for `kern-1` in this case, since it is compiled to point to `/usr/share`.

**Comment by gijzelaerr** [comment] 2017-02-13 08:05
@o-smirnov I have no problems getting the ephemerides stuff to work on KERN-1. Are you sure you are not mixing KERN-dev and KERN-1?

**Comment by gijzelaerr** [comment] 2017-02-13 09:17
so problem is mostly PEBCAK here, and a mistake in setting the SO version in the casacore 2.2.0 is causing us problems where the required dependencies are not automatically forcefully updated.  I'm closing this issue, since we figured out where the problems come from and how to solve them (update the packages). I'll push a new casascore-data to KERN-dev with the right paths.

**Closed as completed by gijzelaerr** 2017-02-13 09:17 UTC

**Comment by o-smirnov** [comment] 2017-02-13 09:29
PEBCAK?

**Comment by olebole** [comment] 2017-02-13 09:42
Problem Exists Between Chair And Keyboard

**Comment by o-smirnov** [comment] 2017-02-13 09:43
LOL I don't need @gijzelaerr's analytical powers to tell me that.
